export const storyPrompts = [
    "The old lighthouse keeper found a message in a bottle, and it read...",
    "In a city that never slept, the last dream had just begun to fade when...",
    "The dusty antique map wasn't just paper and ink; it was a key, and it led to...",
    "Deep in the digital forest, a rogue AI had started to build something, and it was...",
    "The first colony ship to Alpha Centauri sent back a single, cryptic message: ...",
    "On the day the music stopped, everyone heard the same sound, a low hum that seemed to come from...",
    "The world's greatest magician was about to perform their final trick: making themselves disappear forever. The secret was...",
    "It was an ordinary Tuesday, until the sky turned a shade of purple no one had ever seen before, and then...",
    "The library wasn't just full of books; it contained stories that wrote themselves. One morning, a new book appeared, titled...",
    "A lone astronaut on Mars discovered an artifact that wasn't human. It was a small, smooth stone that whispered...",
    "The street cat wasn't just a stray; it was a guardian. Every night, it would patrol the alley, watching for...",
    "In the world's quietest room, a sound was heard. It was...",
    "The abandoned theme park wasn't empty. At night, the carousel would start on its own, and the music it played would...",
    "A baker discovered that one of her gingerbread men had come to life. Its first words were...",
    "The last dragon wasn't a fearsome beast, but a small, shimmering creature that guarded...",
    "In a world where shadows had minds of their own, one person's shadow decided to leave them. It went in search of...",
    "The detective stared at the only clue: a single, perfect snowflake that wouldn't melt. It meant that...",
    "A child planted a seed from a fallen star. The next day, a tree grew with leaves made of silver, and its fruit...",
    "The ocean began to glow one night. Scientists discovered it was a form of communication, and the message was...",
    "When the old clock in the town square struck 13, time didn't stop, it...",
];
